os: osx
osx_image: xcode10.2
language: node_js
node_js: 
  - 12.18.3
cache: npm

install:
  - npm ci

script:
  - npm run electron:build --publish always

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build