os: osx
osx_image: xcode10.2
language: node_js
node_js: 
  - 12.18.3
cache: npm

install:
  - npm ci

script:
  - npm run release --publish always

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  overwrite: true
  file:
    - "ayurvedapp-1.0.0.dmg"
    - "ayurvedapp-1.0.0-mac.zip"
  